import { Company } from '../types';

export const MOCK_COMPANIES: Company[] = [
    {
        id: '1',
        name: 'Veridia AI',
        website: 'https://veridia.ai',
        sector: 'Artificial Intelligence',
        stage: 'Series A',
        location: 'San Francisco, CA',
        description: 'Next-generation ecological monitoring using proprietary AI and satellite imagery.',
    },
    {
        id: '2',
        name: 'Flux Dynamics',
        website: 'https://fluxdynamics.io',
        sector: 'CleanTech',
        stage: 'Seed',
        location: 'Austin, TX',
        description: 'Revolutionizing battery storage with liquid-metal flow batteries for long-duration grid storage.',
    },
    {
        id: '3',
        name: 'NeuralPath Systems',
        website: 'https://neuralpath.systems',
        sector: 'HealthTech',
        stage: 'Series B',
        location: 'Boston, MA',
        description: 'Non-invasive brain-computer interfaces for neurodegenerative disease monitoring.',
    },
    {
        id: '4',
        name: 'QuantumScale',
        website: 'https://quantumscale.com',
        sector: 'Quantum Computing',
        stage: 'Seed',
        location: 'London, UK',
        description: 'Scalable quantum error correction software for the next generation of processors.',
    },
    {
        id: '5',
        name: 'SafeHarbor Security',
        website: 'https://safeharbor.security',
        sector: 'Cybersecurity',
        stage: 'Series C',
        location: 'Tel Aviv, Israel',
        description: 'Zero-trust architecture for decentralized autonomous organizations.',
    },
    {
        id: '6',
        name: 'TerraForma Labs',
        website: 'https://terraformalabs.com',
        sector: 'AgriTech',
        stage: 'Series A',
        location: 'Nairobi, Kenya',
        description: 'Soil regeneration technology using CRISPR-enhanced microbial inoculants.',
    },
    {
        id: '7',
        name: 'OrbitLink',
        website: 'https://orbitlink.space',
        sector: 'SpaceTech',
        stage: 'Late Stage',
        location: 'Los Angeles, CA',
        description: 'Low-latency laser communication mesh for inter-satellite data relay.',
    },
    {
        id: '8',
        name: 'BioSynthix',
        website: 'https://biosynthix.com',
        sector: 'Biotech',
        stage: 'Series B',
        location: 'Berlin, Germany',
        description: 'Synthetic biology platform for carbon-negative textile production.',
    },
    {
        id: '9',
        name: 'Altos Fintech',
        website: 'https://altosfin.tech',
        sector: 'Fintech',
        stage: 'Series A',
        location: 'New York, NY',
        description: 'AI-driven emerging market debt analysis and risk assessment.',
    },
    {
        id: '10',
        name: 'EthicAll',
        website: 'https://ethicall.io',
        sector: 'SaaS',
        stage: 'Seed',
        location: 'Toronto, Canada',
        description: 'Automated ESG compliance and reporting for mid-sized manufacturers.',
    },
];
